
name = "choxanh"
main = "./dist"
compatibility_date = "2023-01-01"

[site]
bucket = "./dist"
entry-point = "dist"

[build]
command = "npm run build"
output_dir = "dist"

[env.production]
workers_dev = false

[env.development]
workers_dev = true